# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
- name: 'pages'
  label: 'Pages'
  editor:
    preview: false
  files:
    - label: 'Hub'
      name: 'about'
      file: 'manual/hubhelp.html'
      fields:
        - { label: 'Title', name: 'title', widget: 'hidden', default: 'default' }
        - { label: 'Layout', name: 'Layout', widget: 'hidden', default: 'default' }
        - { label: 'Body', name: 'body', widget: 'code' }